### ISSUE TITLE
Is there a way to use the system lua?

### ISSUE THREAD

**Issue by vext01** [contextgarden/luametatex#6]
Hi,

OpenBSD TeX Live maintainer here.

Just wondering if there's a way to link the system lua instead of the bundled one?

Thanks

**Comment by hanshagen** [comment]
Hi, 

There are several reasons for not doing this: 

- there is no real gain as lua is small (compared to the other engines luametatex binary is relatively small anyway)

- lua is a language for embedded usage so kind of bound to the target binary; maybe we move with lua (say 5.5), maybe we don't and versions can be different (as in the past); it is rather common to bundle it with the target  

- because there is a heavy draw on lua (in context) having it compiled in the bin also means that we can do link time optimizations and gain some

- we set some 'features' (and/or want to be able to do it independent of what a system does) 

- we use a very recent version of lua (also because we want to test that one - stress tests - and so far that worked well; every update is checked for what got changed / patched) 

- we have the lua source code (small) also in the luametatex source tree so that is the lua instance that we use

- the idea behind luametatex is that eventually it is long term stable;  the reason why we have the source in the context source tree is that users can compile themselves which is relatively easy compared to tex live itself; it is also the reference; by binding the engine source to the distribution users also have a long term working combination  

- luametatex is also a lua compiler (which argues for not using a library); the same binary is used for rendering as for process management (the same for all platforms: windows, linux, bsd). 

- it's not so different from luatex where we also have a specific version of lua (and luajit for luajittex); there are / can be some overloads;  there we use older lua versions (5.4 is not entirely compartble with 5.3 and 5.2 so it is unlikely that we will move to 5.4 soon with luatex) 

Hopefully this clarifies it a bit, 

Hans

**Comment by vext01** [comment]
Thanks Hans.

As long as there's good reason to do so, I'm fine with using the embedded one.

It goes against my packager instincts, but I'm sure it'll be fine.
